name: Android Cloud Build

on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: "Build mode"
        required: true
        default: "release"
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        if: ${{ inputs.build_mode == 'debug' }}
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: ${{ inputs.build_mode == 'release' }}
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: |
            app/build/outputs/apk/**/*.apk
          retention-days: 7
